### ISSUE TITLE
Missing ifdefs in stm32h7rsxx_util_i3c.c

### ISSUE THREAD

**Issue by opkaizen** [STMicroelectronics/stm32h7rsxx_hal_driver#1]
Hello,

The file `stm32h7rsxx_util_i3c.c` does not have the `#ifdef HAL_I3C_MODULE_ENABLED`  that the other HAL components have, which leads to undefined symbols when we compile with I3C module disabled.  Same goes for its corresponding header file if we add the ifdef in the `stm32h7rsxx_util_i3c.c` file after the include (it seems to be done that way in the other sources).

**Comment by KRASTM** [comment]
Hello @opkaizen,

Thank you for the report.

The `#ifdef HAL_xxx_MODULE_ENABLED` used in all HAL component, but the file `stm32h7rsxx_util_i3c.c` it is a helper that contain 2 functions for computation of different timing parameter as mentioned in the brief at the top of the file **"This utility help to calculate the different I3C Timing"**. In other word an extra file could be included when needed, if I3C module used and enabled, with HAL_DRIVER or FULL_LL_DRIVER.

with regards,

**Comment by opkaizen** [comment]
Hello @KRASTM,
I understand this is not directly linked to the I3C module implementation but it is using its symbols, which means we cannot include all the C files as sources in our compilation base if this define is not added.

To give an example of the current issue :
- I'm compiling all C files, whether I'm using all the modules or not
- I don't have to use I3C, so I don't define HAL_I3C_MODULE_ENABLED in the HAL configuration header
- My compiler will say the `stm32h7rsxx_util_i3c.c` has undefined symbols

The workaround could be to force your users to exclude this particular file from the compilation if they don't use it, but it seems to be exactly what these ifdefs are for, aren't they?

**Comment by KRASTM** [comment]
Hello @opkaizen,

You are right, despite that the file is linked to I3C module and it makes no sense to use it without I3C enabled. But we should add the `#ifdef HAL_I3C_MODULE_ENABLED` to prevent those error.

With regards,

**Comment by KRASTM** [comment]
ST Internal Reference: 182462

**Comment by KRASTM** [comment]
Hello @opkaizen,

The issue you reported has been fixed in the frame of version v1.1.0 of the STM32CubeH7RS HAL Driver published recently on GitHub. Thank you again for having reported.

With regards.
