### ISSUE TITLE
JPEG IRQ handler 

### ISSUE THREAD

**Issue by xu-yingjing** [STMicroelectronics/stm32h7rsxx_hal_driver#3]
Hello,

The function JPEG_DMA_ContinueProcess() in file stm32h7rsxx_hal_jpeg.c is only called in the function HAL_JPEG_IRQHandler(), and the function JPEG_DMA_ContinueProcess() calls the function HAL_DMA_Abort() to stop the DMA transfer, but this seems to be an error, In the IRQ handler, the function HAL_DMA_Abort_IT() should be called instead of HAL_DMA_Abort().

**Comment by TOUNSTM** [comment]
ST Internal Reference: 185009

**Comment by TOUNSTM** [comment]
Fixed in db8d9c1dbd38d79e68086d5beed8dd6c922b4d9a
